# General settings
[global]
developmentMode = false
showWarningOnDirectExecution = true

# Theming options
[theme]
base = "light"
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"